name: Deploy Frontend to Windows EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64] 
    steps:
    - name: Checkout frontend code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  

    - name: Install dependencies
      run: npm install
      working-directory: C:\voedu\Voedu-frontend  

    - name: Build frontend
      run: npm run build
      working-directory: C:\voedu\Voedu-frontend

    - name: Start frontend (optional)
      run: npm start
      working-directory: C:\voedu\Voedu-frontend

        "
