name: Deploy Frontend to Windows EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout frontend code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.PRIVATEKEY_FRONTEND }}

    - name: Deploy frontend on EC2
      run: |
        ssh -o StrictHostKeyChecking=no Administrator@44.203.63.89 "
          cd c:/voedu/Voedu-frontend &&
          git pull origin main &&
          npm install &&
          npm run build
        "
